# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
"""Orchestrate the verification checks and assemble the evidence artifact.

``gpu_evidence(worker)`` runs the real-model checks and returns a results dict;
``write_report(...)`` renders the CPU + GPU results to a markdown file that the
PR description can cite.
"""
import logging

from .equivalence import bf16_gemm_demo, logit_equivalence
from .parity import grouped_parity, semantic_parity
from .perf import speed_sweep

logger = logging.getLogger(__name__)


def _table(rows):
    """Plain monospace table from a list of dicts (no pandas dependency)."""
    if not rows:
        return "(empty)"
    cols = list(rows[0].keys())
    w = {c: max(len(str(c)), *(len(str(r[c])) for r in rows)) for c in cols}
    head = "  ".join(str(c).ljust(w[c]) for c in cols)
    body = "\n".join("  ".join(str(r[c]).ljust(w[c]) for c in cols) for r in rows)
    return head + "\n" + body


def gpu_evidence(worker, images=None, prompts=None, verbose=True):
    """Run the real-model evidence suite; return a results dict.

    Covers: bf16-GEMM non-batch-invariance, prefill logit equivalence, detection
    parity (slow/fast/hybrid), throughput, and the one-image-many-queries speedup.
    """
    from .model import sample_images

    if images is None:
        images, prompts = sample_images(4)

    res = {}
    res["bf16_gemm"] = bf16_gemm_demo(device=worker.device, dtype=worker.dtype)
    res["logit_equivalence"] = logit_equivalence(worker, images, prompts)
    res["semantic_parity"] = semantic_parity(worker, images, prompts)
    res["speed"] = speed_sweep(
        worker, images[0], prompts[0], batch_sizes=(1, 2, 4, 8, 16)
    )
    res["multi_parity"] = grouped_parity(worker, images[0], prompts[:4])

    if verbose:
        g = res["bf16_gemm"]
        logger.info(
            "bf16 GEMM batch-invariance: bf16 maxdiff=%.4f  fp32 maxdiff=%.2e  (root cause)",
            g["bf16_maxdiff"],
            g["fp32_maxdiff"],
        )
        le = res["logit_equivalence"]
        logger.info(
            "logit equivalence (scale ~%.1f, padding_clean=%s):\n%s",
            le["logit_scale"],
            le["padding_clean"],
            _table(le["rows"]),
        )
        sp = res["semantic_parity"]
        logger.info(
            "detection parity (slow/hybrid pass=%s, fast struct pass=%s):\n%s",
            sp["slow_hybrid_pass"],
            sp["fast_struct_pass"],
            _table(sp["rows"]),
        )
        logger.info("throughput:\n%s", _table(res["speed"]))
        logger.info(
            "grouped (one-image-many-queries) parity: match=%s",
            res["multi_parity"]["match"],
        )
    return res


def write_report(path, cpu=None, gpu=None, eval_summaries=None):
    """Write a markdown evidence report from CPU and/or GPU results dicts.

    ``eval_summaries`` is the list returned by ``repro.eval_parity`` (per-dataset
    timing/speedup/parity on COCO/LVIS); when present it adds a task-metric
    section.
    """
    lines = [
        "# Reproduced evidence — batched LocateAnything decoding",
        "",
        "_Generated by `repro` (see its README)._",
        "",
    ]
    if cpu is not None:
        lines += [
            "## CPU correctness (fake LM; no GPU, no checkpoint)",
            "",
            "### Parity & batch-independence by mode",
            "```",
            _table(cpu["by_mode"]),
            "```",
            "",
            "### Decode-pattern coverage",
            "```",
            _table(cpu["coverage"]),
            "```",
            "",
            f"**Totals:** {cpu['totals']['parity_pass']}/{cpu['totals']['parity_checks']} "
            f"parity, {cpu['totals']['batch_indep_pass']}/"
            f"{cpu['totals']['batch_indep_checks']} batch-independence, "
            f"{cpu['totals']['eject_pass']}/{cpu['totals']['eject_checks']} early-eject "
            f"(passed={cpu['passed']}).",
            "",
        ]
    if gpu is not None:
        g = gpu["bf16_gemm"]
        lines += [
            "## Real-model (GPU)",
            "",
            f"bf16 GEMM not batch-invariant: bf16={g['bf16_maxdiff']:.4f}, "
            f"fp32={g['fp32_maxdiff']:.2e}.",
            "",
            "### Prefill logit equivalence",
            "```",
            _table(gpu["logit_equivalence"]["rows"]),
            "```",
            "",
            "### Detection parity",
            "```",
            _table(gpu["semantic_parity"]["rows"]),
            "```",
            "",
            "### Throughput — sequential vs batched (N distinct images)",
            "`endtoend_speedup` is this branch's real `predict_batch` wall-clock "
            "win over N sequential `predict_batch([img],[q])` calls on N distinct "
            "image objects. What's inside `batched_s` depends on the checkout: "
            "PR1 batches the vision tower across all N images, PR2 encodes each "
            "image separately. Run on each PR's own notebook for a side-by-side.",
            "```",
            _table(gpu["speed"]),
            "```",
            "",
        ]
    if eval_summaries:
        from .results_table import to_markdown

        lines += [
            "## Task-metric parity on real data (COCO / LVIS)",
            "",
            "Distinct images, greedy decoding, before (B=1) vs after (batched). "
            "Same detections; batched is faster. (AP columns fill in after offline "
            "scoring of the written `preds_before/after.jsonl` with the repo metric.)",
            "",
            to_markdown(eval_summaries),
            "",
        ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path
